config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'

  get '/todos', to: "todos#index", as: "todos"

  post '/todos', to: "todos#create"

  delete '/todos', to: "todos#delete"

  delete '/todos/:todo', to: "todos#delete_one", as: "delete_one"
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = session[:todos] ||= []
  end

  def create
  #add a todo to the session [:todo]
  session[:todos] << params[:task]
  redirect_to '/todos'
  end

  def delete
    #clear the session [:todos]
    session[:todos] = nil

    redirect_to '/todos'
  end

  def delete_one
    session[:todos].delete(params[:todo])
    redirect_to '/todos'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todosession</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body class = "container text-center">

<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-success" %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
   <h1>To Do List</h1>
<ol>
  <% @todos.each do |todo| %>
  <li>
  <%= todo %>
  <%= button_to "X", delete_one_path(todo), :method => :delete %> 
  </li>

  <% end %>
</ol>
   <%= form_tag(todos_path) do %>
     <p>
      <%= label_tag(:task) %>
      <%= text_field_tag(:task, nil, autofocus: true) %>
    </p>
     <%= submit_tag "Add"%>
  <% end %>


 <%= link_to "Delete", todos_path, method: "delete" %>